config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'chats/new'
  get 'chats/show/:id' => 'chats#show'
   get'chats/buying/:id' => 'chats#buying'

  post 'chats' => 'chats#create'
  post 'chats/reply' => 'chats#reply'
  post 'chats/buy' => 'chats#buy'
  get 'chats/:id' => 'chats#index', :as => 'chats_inbox'

  get 'chats/update'

  get 'chats/destroy'

  get 'pages/:id' => 'pages#index'
  resources :products

  post 'products/watch' => 'products#watch'
  post 'products/unwatch' => 'products#unwatch'

  get 'products/:id' => 'products#show'

  devise_for :users, :controllers => { :omniauth_callbacks => "sessions",
    registrations: 'registrations' }
  resources :users, only: [:show, :edit]

  get '/users/:id/index' => 'users#index' , as: :user_profile

  post 'users/:id/follow' => 'users#follow', as: :follow_user
  delete 'users/:id/follow' => 'users#unfollow'

  post 'users/:id/review' => 'users#review', as: :review_user

  get '/mains/:id/posts' => 'mains#posts'
  resources :mains

  root 'products#index'

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :user
  belongs_to :productchat
end

app/models/condition.rb
class Condition < ActiveRecord::Base
	has_many :products
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :condition
  has_many :watchlists, dependent: :destroy
  has_many :productchats, dependent: :destroy
  has_many :chats, through: :productchat

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", large: "600x600" }
  validates :title, :price, :description, :condition_id, :category_id, presence: true
  validates :price_fixed, inclusion: [true, false]
  validates :avatar, attachment_presence: true
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  self.per_page = 10

  geocoded_by :location
  after_validation :geocode, :if => :location_changed?

end

app/models/productchat.rb
class Productchat < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  has_many :chats, dependent: :destroy
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

  # validate :no_rate_self

  def no_rate_self
    errors.add(:rateable, "can't rate yourself") if rateable.is_a?(rateable_type) and user.id == rateable.id
  end

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  ratyrate_rater
  ratyrate_rateable "user_review"
  
  has_many :products
  has_many :watchlists
  has_many :productchats, dependent: :destroy
  has_many :chats, through: :productchat

  has_many :buyproducts, through: :productchats, source: :product
  has_many :watchproducts, through: :watchlists, source: :product

  has_many :user_follows, dependent: :destroy
  has_many :follows, through: :user_follows, source: :follow

  has_many :user_reviews, dependent: :destroy
  has_many :reviewers, through: :user_reviews, source: :reviewuser

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

    def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.email =  auth.info.email
			user.password = Devise.friendly_token[0,20]
			user.name = auth.info.name   # assuming the user model has a name
			user.image = auth.info.image # assuming the user model has an image
		end
	end

	def self.new_with_session(params, session)
		super.tap do |user|
			if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
				user.email = data["email"] if user.email.blank?
			end
		end
	end

	acts_as_messageable

	def mailboxer_name
    	self.name
  	end

  	def mailboxer_email(object)
    	self.email
  	end

end

app/models/user_follow.rb
class UserFollow < ActiveRecord::Base
  belongs_to :user, class_name: 'User'
  belongs_to :follow, class_name: 'User'

  validates :user, :follow, presence: true
  validate :no_follow_self

  def no_follow_self
    errors.add(:follow, "can't follow yourself") if user == follow
  end
end

app/models/user_review.rb
class UserReview < ActiveRecord::Base
  belongs_to :user, class_name: 'User'
  belongs_to :reviewuser, class_name: 'User'

  validates :user, :reviewuser, :review, presence: true
  validate :no_review_self

  def no_review_self
    errors.add(:reviewuser, "can't review yourself") if user == reviewuser
  end

end

app/models/watchlist.rb
class Watchlist < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  
  before_action :authenticate_user!

  def new
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:notice] = "Your message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user).order("created_at ASC")
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end


  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end


  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body,recipients:[])
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
  end

	def flash_class(level)
    case level.to_sym
      when :notice then "alert alert-success"
      when :info then "alert alert-info"
      when :alert then "alert alert-danger"
      when :warning then "alert alert-warning"
    end
  end

  def active_page(active_page)
    @active == active_page ? "active" : ""
  end

  def conditions_option()
    options = []
    conditions = Condition.all
    conditions.each do |c|
      options.push([c.name, c.id])
    end
    return options
  end

  def categories_option()
    options = []
    categories = Category.all
    categories.each do |c|
      options.push([c.name, c.id])
    end
    return options
  end


  def product_watch(product_id, user_id)
    product = Product.find(product_id)
    product_watch = Watchlist.where product_id: product
    if product_watch.find_by user_id: user_id
      return true
    else
      return false
    end
  end
  
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
	def unread_messages_count
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_location
	    @location ||= Geocoder.search(remote_ip)[0].address
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="http://placehold.it/64x64" alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.name %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "View", conversation_path(conversation)  %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients %>
      <%= f.select(:recipients, User.all.collect {|p| [ p.name, p.id ] }, {}, { multiple: true , class: "chosen-select form-control" })%>
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-success" %>

<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <a href="#">
          <!-- <img class="media-object" src="http://placehold.it/64x64" alt="..."> -->
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.name %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<div class="row">
  <div style="margin-top:100px;"></div>
  <div class="spacer"></div>
  <div class="col-md-6">
    <%= link_to new_conversation_path do %>
        <span class="btn btn-success">
          <em class="fa fa-pencil fa-lg"></em>
          Compose
        </span>
    <% end %>
  </div>
  <div class="col-md-6 text-right">
    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
    <% else %>
        
    <%= link_to( trash_conversation_path(conversation), method: :post,
                    data: {confirm: 'Are you sure?'} ) do %>
          <span class="btn btn-danger">
            <em class="fa fa-trash-o fa-lg"></em>
              Move to trash
          </span>
    <% end %>

    <% end %>
  </div>
</div>

<div class="row" style="margin-top:10px;">
  <div class="spacer"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>