config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'chats/new'
  get 'chats/show/:id' => 'chats#show'
   get'chats/buying/:id' => 'chats#buying'

  post 'chats' => 'chats#create'
  post 'chats/reply' => 'chats#reply'
  post 'chats/buy' => 'chats#buy'
  get 'chats/:id' => 'chats#index', :as => 'chats_inbox'

  get 'chats/update'

  get 'chats/destroy'

  get 'pages/:id' => 'pages#index'
  resources :products

  post 'products/watch' => 'products#watch'
  post 'products/unwatch' => 'products#unwatch'

  get 'products/:id' => 'products#show'

  devise_for :users, :controllers => { :omniauth_callbacks => "sessions",
    registrations: 'registrations' }
  resources :users, only: [:show, :edit]

  get '/users/:id/index' => 'users#index' , as: :user_profile

  post 'users/:id/follow' => 'users#follow', as: :follow_user
  delete 'users/:id/follow' => 'users#unfollow'

  post 'users/:id/review' => 'users#review', as: :review_user

  get '/mains/:id/posts' => 'mains#posts'
  resources :mains

  root 'products#index'

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  ratyrate_rater
  ratyrate_rateable "user_review"
  
  has_many :products
  has_many :watchlists
  has_many :productchats, dependent: :destroy
  has_many :chats, through: :productchat

  has_many :buyproducts, through: :productchats, source: :product
  has_many :watchproducts, through: :watchlists, source: :product

  has_many :user_follows, dependent: :destroy
  has_many :follows, through: :user_follows, source: :follow

  has_many :user_reviews, dependent: :destroy
  has_many :reviewers, through: :user_reviews, source: :reviewuser

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

    def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.email =  auth.info.email
			user.password = Devise.friendly_token[0,20]
			user.name = auth.info.name   # assuming the user model has a name
			user.image = auth.info.image # assuming the user model has an image
		end
	end

	def self.new_with_session(params, session)
		super.tap do |user|
			if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
				user.email = data["email"] if user.email.blank?
			end
		end
	end

	acts_as_messageable

	def mailboxer_name
    	self.name
  	end

  	def mailboxer_email(object)
    	self.email
  	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index

		# ======= Hard code because unstable API ======
	    @location = "Bellevue, WA 98004, United States"
	    # Format location for readability
	    # @location = current_location
	    21.times do
	      @location.chop!
	    end

	    @search_coordinates = Geocoder.coordinates(@location)
	    # =============================================

		@curuser = current_user;
		@seller = User.find(params[:id])
		@product = User.find(@curuser.id).products.last
		@products = User.find(@seller.id).products
		if current_user
			@following = UserFollow.find_by(user_id: @curuser.id, follow_id: @seller.id)
		end
		@followers = UserFollow.where(follow_id: @seller.id)
		@rating = Rate.find_by(rater_id: @curuser.id, rateable_id: params[:id], rateable_type: "User")
		@review = @seller.user_reviews.find_by(reviewuser_id: @curuser.id)
		@reviews = @seller.user_reviews.limit(10).order("updated_at DESC")
	end

	def show
		# Testing purpose
		@user = User.find(params[:id])
		@users = User.all.includes(:user_reviews)
		@follows = @user.follows
		@followmes = UserFollow.includes(:user).where(follow_id: params[:id])
		@myreviews = UserReview.includes(:user).where(user_id: params[:id])
	end

	def follow
		@user = User.find(params[:id])
		@user.user_follows.create(follow: User.find(params[:follow]))
		puts "original_url"
		puts request.original_url
		if params[:product_id]
			puts "product"
			redirect_to product_path(params[:product_id])
		else
			redirect_to "/users/#{params[:follow]}/index"
		end
	end

	def unfollow
		@user = User.find(params[:id])
		puts "original_url"
		puts request.original_url
		@user.user_follows.find_by(follow_id: params[:follow]).destroy
		if params[:product_id]
			puts "product"
			redirect_to product_path(params[:product_id])
		else
			redirect_to "/users/#{params[:follow]}/index"
		end
	end

	def review
		@reviewer = current_user
		@user = User.find(params[:id])
		@review = @user.user_reviews.find_by(reviewuser_id: @reviewer.id)
		if @review
			@review.update(review: params[:review])
		else
			@user.user_reviews.create(reviewuser_id: @reviewer.id, review: params[:review])
		end
		redirect_to :back
	end

	def edit
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div id="master_container" class="col-sm-6 col-md-offset-1">
	<div class="panel panel-default">
		  <div id="header" class="panel-body">
			  <h4><%= @seller.name %>'s Offers</h4>
		  </div>
	</div>
		<div class="scroll panel panel-default">
	    	<div id="masonry-container" class="transitions-enabled clearfix">
	          	<%= render @products %>
	    	</div>
	  	</div>
</div>
<div id="master_container" class="col-sm-3 col-sm-offset-1">
	<div class="panel panel-default">
		<div class="panel-heading">
		    <h3 id="asking" class="panel-title text-center">Seller</h3>
		</div>
		<div class="panel-body text-center">
			<img src='https://graph.facebook.com/<%= @seller.uid %>/picture?type=large' alt='picture'>
			<h3>
				<% if @rating %>
					<div class="rating_star" style="display:inline-block;">
						<%= rating_for @seller, "user_review", imdb_avg: true %>
					</div>
				<% end %>
				<%= @seller.name %>
			</h3>
		</div>
	</div>
	<% if @seller != current_user %>
		<div class="panel panel-default">
			<div class="panel-heading">
					<h3 id="asking" class="panel-title text-center">Your Review</h3>
			</div>
			<div class="panel-body text-center">
				<%= rating_for @seller, "user_review", :disable_after_rate => false, stars: 5 %>	
				<h4>Detail Review</h4>
				<form action="/users/<%=@seller.id%>/review" method="post">
					<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">
					<textarea name="review" rows="4" col="20" style="width:100%; border-radius:5px;padding:5px;margin: 5px 0;" class="form-control"><%= @review.review if @review %></textarea>
					<input type="submit" value="Update Review" class="form-control btn btn-primary" style="border-radius: 5px">
				</form>
			</div>
		</div>
	<% end %>

	<div class="panel panel-default">
		<div class="panel-heading">
				<h3 id="asking" class="panel-title text-center">Top 10 Recent Reviews</h3>
		</div>
		<div class="panel-body text-center">
			<% @reviews.each do |r| %>
			<div>
				<i>-- <%= r.review %></i>
			</div>
			<% end %>
		</div>
	</div>

	<div class="panel panel-default">
		<div class="panel-heading">
			<% 21.times do %>
				<% @product.location.chop! if @product %>
			<% end %>
		    <h3 class="panel-title text-center"><%= @product.location if @product%></h3>
		</div>
		<div id="googleMap" class="panel-body" style="height:300px"></div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">
		    <h3 class="panel-title text-center">Followers (<%= @followers.count %>)</h3>
	 	</div>
		<div class="panel-body">
	    <% @followers.each do |follower| %>
		    <a href="/users/<%= follower.user.id %>/index"><img src="<%= follower.user.image %>" alt="<%=  follower.user.name %>" /></a>
	    <% end %>
	  </div>
	  <div class="panel-body">
		  	<% if user_signed_in? && current_user.id != @seller.id %>
			  	<% if @following %>
	              <%= link_to 'Unfollow', follow_user_path(:id => current_user.id , :follow => @seller.id), method: :delete, class:"btn btn-danger btn-block btn-lg"%>
	            <% else %>
	              <%= link_to 'Follow', follow_user_path(:id => current_user.id, :follow => @seller.id), method: :post, class:"btn btn-primary btn-block btn-lg"%>
	            <% end %>
	        <% end %>
		</div>
	</div>
</div>
<script>
$("#googleMap").html("<%= escape_javascript(render partial: 'partials/googleMap') %>");

$(function(){

var $container = $('#masonry-container');

$container.imagesLoaded(function(){
  $container.masonry({
    itemSelector: '.box',
    columnWidth: 100
  });
});

$container.infinitescroll({
  navSelector  : '.pagination',    // selector for the paged navigation
  nextSelector : '.pagination .next_page a',  // selector for the NEXT link (to page 2)
  itemSelector : '.box',     // selector for all items you'll retrieve
  loading: {
      finishedMsg: 'No more pages to load.',
      img: 'http://i.imgur.com/6RMhx.gif'
    }
  },
  // trigger Masonry as a callback
  function( newElements ) {
    // hide new items while they are loading
    var $newElems = $( newElements ).css({ opacity: 0 });
    // ensure that images load before adding to masonry layout
    $newElems.imagesLoaded(function(){
      // show elems now they're ready
      $newElems.animate({ opacity: 1 });
      $container.masonry( 'appended', $newElems, true );
    });
  }
);

});
</script>

app/views/users/show.html.erb
<div class="container">
  <div style="margin-top:75px">

  </div>
  <div class="row">
    <h2>Current User:</h2>
    <table class="table">
      <tr>
        <td class="col-md-1">
          <img src="<%=  @user.image %>" alt="<%=  @user.name %>" />
        </td>
        <td class="col-md-1">
          <h4><%=  @user.name %></h4>
        </td>
      </tr>
    </table>
    <% @myreviews.each do |r| %>
      <%= r.reviewuser.name %> : <%= r.review %>
    <% end %>
  </div>

  <div class="row">
    <h2>All Other Users:</h2>
    <% @users.each do |u| %>
      <% if u.id != @user.id %>
        <table class="table">
          <tr>
            <td class="col-md-1">
              <img src="<%= u.image %>" alt="<%= u.name %>" />
            </td>
            <td class="col-md-1">
              <h4>
                <%= link_to u.name, user_path(u)%>
              </h4>
            </td>
            <td class="col-md-1">
              <% if @follows and @follows.exists?(id: u.id) %>
                <%= link_to 'Unfollow', follow_user_path(:follow => u), method: :delete, class:"btn btn-danger"%>
              <% else %>
                <%= link_to 'Follow', follow_user_path(:follow => u), method: :post, class:"btn btn-primary"%>
              <% end %>
            </td>
          </tr>
        </table>
        <!-- <% if false %>
          <div class="row">

            <div class="col-md-3">
              <form action="/users/<%=u.id%>/review" method="post">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <input type="hidden" name="user_id" value="<%=@user.id%>">
                <textarea name="review"rows="3" cols="40" class="form-control"></textarea>
                <input type="submit" value="New Review" class="form-control">
              </form>
            </div>

            <div class="col-md-6">
              <% u.user_reviews.each do |r| %>
                <div>
                  <% if r.reviewuser %>
                    <%= r.reviewuser.name %> : <%= r.review %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %> -->
      <% end %>
    <% end %>
  </div>

  <div class="row">
    <h2>Following:</h2>
    <table class="table">
    <% @follows.each do |u| %>
      <tr>
        <td class="col-md-1">
          <img src="<%= u.image %>" alt="<%= u.name %>" />
        </td>
        <td class="col-md-1">
          <h4><%= u.name %></h4>
        </td>
      </tr>
    <% end %>
    </table>
  </div>

  <div class="row">
    <h2>Who Followed Me:</h2>
    <table class="table">
    <% @followmes.each do |u| %>
      <tr>
        <td>
          <img src="<%= u.user.image %>" alt="<%= u.user.name %>" />
        </td>
        <td>
          <h4><%= u.user.name %></h4>
        </td>
      </tr>
    <% end %>
    </table>
  </div>
</div>