config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'chats/new'
  get 'chats/show/:id' => 'chats#show'
   get'chats/buying/:id' => 'chats#buying'

  post 'chats' => 'chats#create'
  post 'chats/reply' => 'chats#reply'
  post 'chats/buy' => 'chats#buy'
  get 'chats/:id' => 'chats#index', :as => 'chats_inbox'

  get 'chats/update'

  get 'chats/destroy'

  get 'pages/:id' => 'pages#index'
  resources :products

  post 'products/watch' => 'products#watch'
  post 'products/unwatch' => 'products#unwatch'

  get 'products/:id' => 'products#show'

  devise_for :users, :controllers => { :omniauth_callbacks => "sessions",
    registrations: 'registrations' }
  resources :users, only: [:show, :edit]

  get '/users/:id/index' => 'users#index' , as: :user_profile

  post 'users/:id/follow' => 'users#follow', as: :follow_user
  delete 'users/:id/follow' => 'users#unfollow'

  post 'users/:id/review' => 'users#review', as: :review_user

  get '/mains/:id/posts' => 'mains#posts'
  resources :mains

  root 'products#index'

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
  
  before_action :authenticate_user!

	def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end
  
end

app/helpers/mailbox_helper.rb
module MailboxHelper
	def unread_messages_count
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/views/mailbox/_folder_view.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-12">
    <div style="margin-top:100px;"></div>
    <%= link_to new_conversation_path do %>
        <span class="btn btn-success">
        <em class="fa fa-pencil fa-lg"></em>
        Compose</span>
    <% end %>

    <div class="spacer"></div>
  </div>
  
  <div class="col-md-4" style="margin-top: 10px;">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8" style="margin-top: 10px;">
    <div class="panel panel-default">
      <div class="panel-body">
        <% if is_conversation %>
            <%= render 'conversations/form' %>
        <% else %>
            <% if messages.any? %>
            <%= render partial: 'conversations/conversation', collection: messages %>
            <% else %>
            <h4 class="text-center">Empty</h4>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/mailbox/_folders.html.erb
<ul class="nav nav-pills nav-stacked">
  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailbox_inbox_path do  %>
        <span class="label label-danger pull-right"><%=unread_messages_count%></span>
        <em class="fa fa-inbox fa-lg"></em>
        <span>Inbox</span>
    <% end %>
  </li>
  <li class="<%= active_page(:sent) %>">
    <%= link_to mailbox_sent_path do %>

        <em class="fa fa-paper-plane-o fa-lg"></em>
        <span>Sent</span>
    <% end %>
  </li>

  <li class="<%= active_page(:trash) %>">
    <%= link_to mailbox_trash_path do %>
        <em class="fa fa-trash-o fa-lg"></em>
        <span>Trash</span>
    <% end %>
  </li>
</ul>

app/views/mailbox/inbox.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox } %>

app/views/mailbox/sent.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent } %>

app/views/mailbox/trash.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash } %>