config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'chats/new'
  get 'chats/show/:id' => 'chats#show'
   get'chats/buying/:id' => 'chats#buying'

  post 'chats' => 'chats#create'
  post 'chats/reply' => 'chats#reply'
  post 'chats/buy' => 'chats#buy'
  get 'chats/:id' => 'chats#index', :as => 'chats_inbox'

  get 'chats/update'

  get 'chats/destroy'

  get 'pages/:id' => 'pages#index'
  resources :products

  post 'products/watch' => 'products#watch'
  post 'products/unwatch' => 'products#unwatch'

  get 'products/:id' => 'products#show'

  devise_for :users, :controllers => { :omniauth_callbacks => "sessions",
    registrations: 'registrations' }
  resources :users, only: [:show, :edit]

  get '/users/:id/index' => 'users#index' , as: :user_profile

  post 'users/:id/follow' => 'users#follow', as: :follow_user
  delete 'users/:id/follow' => 'users#unfollow'

  post 'users/:id/review' => 'users#review', as: :review_user

  get '/mains/:id/posts' => 'mains#posts'
  resources :mains

  root 'products#index'

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :user
  belongs_to :productchat
end

app/models/condition.rb
class Condition < ActiveRecord::Base
	has_many :products
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :condition
  has_many :watchlists, dependent: :destroy
  has_many :productchats, dependent: :destroy
  has_many :chats, through: :productchat

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", large: "600x600" }
  validates :title, :price, :description, :condition_id, :category_id, presence: true
  validates :price_fixed, inclusion: [true, false]
  validates :avatar, attachment_presence: true
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  self.per_page = 10

  geocoded_by :location
  after_validation :geocode, :if => :location_changed?

end

app/models/productchat.rb
class Productchat < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  has_many :chats, dependent: :destroy
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

  # validate :no_rate_self

  def no_rate_self
    errors.add(:rateable, "can't rate yourself") if rateable.is_a?(rateable_type) and user.id == rateable.id
  end

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  ratyrate_rater
  ratyrate_rateable "user_review"
  
  has_many :products
  has_many :watchlists
  has_many :productchats, dependent: :destroy
  has_many :chats, through: :productchat

  has_many :buyproducts, through: :productchats, source: :product
  has_many :watchproducts, through: :watchlists, source: :product

  has_many :user_follows, dependent: :destroy
  has_many :follows, through: :user_follows, source: :follow

  has_many :user_reviews, dependent: :destroy
  has_many :reviewers, through: :user_reviews, source: :reviewuser

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

    def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.email =  auth.info.email
			user.password = Devise.friendly_token[0,20]
			user.name = auth.info.name   # assuming the user model has a name
			user.image = auth.info.image # assuming the user model has an image
		end
	end

	def self.new_with_session(params, session)
		super.tap do |user|
			if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
				user.email = data["email"] if user.email.blank?
			end
		end
	end

	acts_as_messageable

	def mailboxer_name
    	self.name
  	end

  	def mailboxer_email(object)
    	self.email
  	end

end

app/models/user_follow.rb
class UserFollow < ActiveRecord::Base
  belongs_to :user, class_name: 'User'
  belongs_to :follow, class_name: 'User'

  validates :user, :follow, presence: true
  validate :no_follow_self

  def no_follow_self
    errors.add(:follow, "can't follow yourself") if user == follow
  end
end

app/models/user_review.rb
class UserReview < ActiveRecord::Base
  belongs_to :user, class_name: 'User'
  belongs_to :reviewuser, class_name: 'User'

  validates :user, :reviewuser, :review, presence: true
  validate :no_review_self

  def no_review_self
    errors.add(:reviewuser, "can't review yourself") if user == reviewuser
  end

end

app/models/watchlist.rb
class Watchlist < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
  end

	def flash_class(level)
    case level.to_sym
      when :notice then "alert alert-success"
      when :info then "alert alert-info"
      when :alert then "alert alert-danger"
      when :warning then "alert alert-warning"
    end
  end

  def active_page(active_page)
    @active == active_page ? "active" : ""
  end

  def conditions_option()
    options = []
    conditions = Condition.all
    conditions.each do |c|
      options.push([c.name, c.id])
    end
    return options
  end

  def categories_option()
    options = []
    categories = Category.all
    categories.each do |c|
      options.push([c.name, c.id])
    end
    return options
  end


  def product_watch(product_id, user_id)
    product = Product.find(product_id)
    product_watch = Watchlist.where product_id: product
    if product_watch.find_by user_id: user_id
      return true
    else
      return false
    end
  end
  
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
	def unread_messages_count
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_location
	    @location ||= Geocoder.search(remote_ip)[0].address
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_login.html.erb
<!--login modal-->
<div id="loginModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control', autofocus: true %>
          </div>

          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control', autocomplete: "off" %>
          </div>

          <% if devise_mapping.rememberable? -%>
            <div class="form-group">
              <%= f.check_box :remember_me %>
              <%= f.label :remember_me %>
            </div>
          <% end -%>

          <div class="form-group">
            <%= f.submit "Log in", class: 'btn btn-primary form-control' %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
          <div class="col-md-12">
            <%= link_to "Connect with Facebook", user_omniauth_authorize_path(:facebook), class: "btn btn-primary btn-lg" %>
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
          </div>  
      </div>
  </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" id="height_nav">
  <div class="navbar-header">
    <button class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/"><%= image_tag("logo.png")  %></a>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-left">

      <%= form_tag products_path, :method => :get, class: 'navbar-form', role:'search' do %>
      <div class="form-group">
        <%= text_field_tag :search_products, params[:search_products], :id => 'search-input', class: 'form-control', :style => 'border-radius:10px'%>
      </div>

      <div class="form-group">
        <a href="">
          <i class="fa fa-map-marker fa-lg" style="color: black"></i>
        </a>
        <%= text_field_tag :search_location, params[:search_location], :id => 'geo-input', class: 'form-control', :style => 'border-radius: 10px', :value => @location %>
      </div>

      <%= submit_tag "Search", :name => nil, class: 'btn btn-default btn-sm form-control', :style => 'border-radius:10px'%>

      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <a href="/mains/show" id="font_color">About</a>
      </li>
      <% if user_signed_in? %>
      <li>
        <!-- role="button" data-toggle="modal"  -->
        <a href="/mains/<%= current_user.id %>/posts" id="font_color">Posts</a>
      </li>
      <li class="dropdown" id="fat-menu">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="padding:5px;">
          <img class="profile-img" src="<%= current_user.image %>" style="width:40px;height:40px">
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", user_profile_path(current_user) %></li>
          <li><%= link_to "Inbox", chats_inbox_path(current_user) %></li>
          <li><%= link_to "Settings", edit_user_registration_path %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
          </li>
        </ul>
      </li>
      <% else %>
      <li>
        <a data-toggle="modal" href="#loginModal" id="font_color" role="button">Login</a>
      </li>
      <li>
        <a data-toggle="modal" href="#signupModal" id="font_color" role="button">Sign up</a>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

<script type="text/javascript">
$(document).ready(function () {
  $('.dropdown-toggle').dropdown();
  $("#geo-input").geocomplete();
  $("#geo-input").text("<%= @location %>");
});
</script>

app/views/layouts/_signup.html.erb
<!--signup modal-->
<div id="signupModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>
      <div class="modal-body">
            <%= form_for(resource, as: resource_name, url: registration_path(resource_name), remote: true) do |f| %>

              <%= devise_error_messages! %>

                <div id="errors_div"></div>
                <div class="form-group">
                  <%= f.label :email %>
                  <%= f.email_field :email, class: 'form-control', autofocus: true %>
                </div>

                <div class="form-group">
                  <%= f.label :password %>
                  <% if @minimum_password_length %>
                    <em>(<%= @minimum_password_length %> characters minimum)</em>
                  <% end %><br />
                  <%= f.password_field :password, class: 'form-control', autocomplete: "off" %>
                </div>

                <div class="form-group">
                  <%= f.label :password_confirmation %>
                  <%= f.password_field :password_confirmation, class: 'form-control', autocomplete: "off" %>
                </div>

                <div class="form-group">
                  <%= f.submit "Sign up", class: 'btn btn-primary form-control' %>
                </div>
            <% end %>
      </div>
      <div class="modal-footer">
          <div class="col-md-12">
            <%= link_to "Connect with Facebook", user_omniauth_authorize_path(:facebook), class: "btn btn-primary btn-lg" %>
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
          </div>  
      </div>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Kwikpost</title>
    <meta name="generator" content="Bootply" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>


</head>

<body>
  <div id="top_nav" class="header">
    <%= render 'layouts/nav' %>
  </div>

  <%= yield %>

  <%= render 'layouts/signup' %>
  <%= render 'layouts/login' %>
</body>
</html>

app/views/layouts/errors.js.erb
<% if !resource.errors.full_messages.empty? %>
$("#errors_div").html("<%= resource.errors.full_messages %>");
<% else %>
$('#signupModal').modal('hide');
location.reload();
<% end %>

app/views/partials/_buying.html.erb
<h1>Buying</h1>

<div id="masonry-container" class="transitions-enabled clearfix centered">
	<%= render current_user.buyproducts %>
</div>

app/views/partials/_googleMap.html.erb
    <style>
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #map {
        height: 100%;
      }
    </style>
    <div id="map"></div>
    <script>

// This example creates circles on the map, representing populations in North
// America.

// First, create an object containing LatLng and population for each city.
var citymap = {
  location: {
    center: {lat: <%= @product.latitude if @product %>, lng: <%= @product.longitude if @product %>}
  }
};

function initMap() {
  // Create the map.
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 12,
    center: {lat: <%= @product.latitude if @product %>, lng: <%= @product.longitude if @product%>},
    mapTypeControl: false,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });

  // Construct the circle for each value in citymap.
  // Note: We scale the area of the circle based on the population.
  for (var city in citymap) {
    // Add the circle for this city to the map.
    var cityCircle = new google.maps.Circle({
      strokeColor: '#FF0000',
      strokeOpacity: 0.8,
      strokeWeight: 2,
      fillColor: '#FF0000',
      fillOpacity: 0.35,
      map: map,
      center: citymap[city].center,
      radius: 1000
    });
  }
}

</script>
<script async defer
  src="https://maps.googleapis.com/maps/api/js?signed_in=false&callback=initMap">
</script>

app/views/partials/_new.html.erb
<%= form_for @product, :url => products_path, :html => {:multipart => true} do |f| %>
  <div class="form-group">
	  <%= f.label :avatar, "Upload Picture" %>
	  <%= f.file_field :avatar, class: "form-control"%>
  </div>
  <div class="form-group">
	  <%= f.label :title, "Title:" %>
	  <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
	  <%= f.label :price, "Price:" %>
		  <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
	  <%= f.label :description, "Description:" %>
		  <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
	  <%= f.label :price_fixed, "Price fixed:" %>
		  <%= f.select :price_fixed,
        options_for_select([ [ 'Yes', true], [ 'No', false] ], true), {}, class: "form-control"%>
  </div>
  <div class="form-group">
	  <%= f.label :category_id, "Category:" %>
  	<%= f.select :category_id, options_for_select(categories_option), {}, class: "form-control"  %>
  </div>
  <div class="form-group">
	  <%= f.label :condition_id, "Condition:" %>
		<%= f.select :condition_id, options_for_select(conditions_option), {}, class: "form-control" %>
  </div>
  <button type="submit" name="commit" class="btn btn-primary form-control">Submit</button>
<% end %>
<% if flash[:errors] %>
	<% flash[:errors].each do |error| %>
  <div class="alert alert-success" role="alert"><%= error %></div>
	<% end %>
<% end %>

app/views/partials/_selling.html.erb
<h1>Selling</h1>

<div id="masonry-container" class="transitions-enabled clearfix centered">
	<%= render @products %>
</div>

app/views/partials/_watching.html.erb
<h1>Watching</h1>
<div id="masonry-container" class="transitions-enabled clearfix centered">
	<%= render current_user.watchproducts %>
</div>